services:
  - type: web
    name: swapsnap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: BASE_URL
        value: https://swapsnap.studyshare.pl
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1
    autoDeploy: true  # Enable auto-deployment
    branch: main      # Branch to watch for changes
    healthCheckPath: /health  # Path to check if service is healthy
    numInstances: 1   # Number of instances to run
    domains:
      - swapsnap.studyshare.pl
