services:
  - type: web
    name: swapsnap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: BASE_URL
        value: https://swapsnap.studyshare.pl
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1
    autoDeploy: true
    branch: main
    healthCheckPath: /health
    numInstances: 1
    domains:
      - swapsnap.studyshare.pl
